/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.botonantipanico.Receptor;

import java.awt.event.ActionListener;
import javax.swing.DefaultListModel;
import models.Solicitud;

/**
 *
 * @author franc
 */
public class vistaReceptor extends javax.swing.JFrame implements IVistaReceptor{

    /**
     * Creates new form vistaReceptor
     */
    public vistaReceptor() {
        initComponents();
        this.modeloListaSolicitudes = new DefaultListModel<Solicitud>();
        this.listaSolicitudes.setModel(this.modeloListaSolicitudes);
        this.recibidoButton.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        recibidoButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaSolicitudes = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        infoTextArea = new javax.swing.JTextArea();
        solicitudesLabel = new javax.swing.JLabel();
        informacionLabel = new javax.swing.JLabel();
        iniciarConexionButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        editMenu = new javax.swing.JMenu();
        configurationButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receptor");

        recibidoButton.setText("Eliminar");
        recibidoButton.setActionCommand("eliminarSolicitud");
        recibidoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recibidoButtonMouseClicked(evt);
            }
        });
        recibidoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recibidoButtonActionPerformed(evt);
            }
        });

        listaSolicitudes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listaSolicitudesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(listaSolicitudes);

        infoTextArea.setColumns(20);
        infoTextArea.setRows(5);
        jScrollPane3.setViewportView(infoTextArea);

        solicitudesLabel.setText("Solicitudes");

        informacionLabel.setText("Informacion");

        iniciarConexionButton.setText("INICIAR CONEXION");
        iniciarConexionButton.setActionCommand("iniciarConexion");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(solicitudesLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(recibidoButton)
                                    .addComponent(iniciarConexionButton)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(informacionLabel)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(solicitudesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(iniciarConexionButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recibidoButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informacionLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        editMenu.setText("Edit");
        editMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editMenuActionPerformed(evt);
            }
        });

        configurationButton.setText("Configuracion");
        configurationButton.setActionCommand("configurationOpen");
        configurationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurationButtonActionPerformed(evt);
            }
        });
        editMenu.add(configurationButton);

        jMenuBar1.add(editMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void recibidoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recibidoButtonActionPerformed

    }//GEN-LAST:event_recibidoButtonActionPerformed

    private void editMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editMenuActionPerformed

    private void configurationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurationButtonActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_configurationButtonActionPerformed

    private void listaSolicitudesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listaSolicitudesValueChanged
        this.recibidoButton.setEnabled(true);
        Solicitud sol=this.getSolicitudSelected();
        if(sol!=null)
            this.updateTextArea(sol.getInfo());
        else
            this.updateTextArea("");
    }//GEN-LAST:event_listaSolicitudesValueChanged

    private void recibidoButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recibidoButtonMouseClicked

    }//GEN-LAST:event_recibidoButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaReceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaReceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaReceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaReceptor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaReceptor().setVisible(true);
            }
        });
    }
    
      
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem configurationButton;
    private javax.swing.JMenu editMenu;
    private javax.swing.JTextArea infoTextArea;
    private javax.swing.JLabel informacionLabel;
    private javax.swing.JButton iniciarConexionButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<Solicitud> listaSolicitudes;
    private javax.swing.JButton recibidoButton;
    private javax.swing.JLabel solicitudesLabel;
    // End of variables declaration//GEN-END:variables

    /*Componentes declarados por nosotros manualmente*/
    private DefaultListModel<Solicitud> modeloListaSolicitudes;
    
    
    @Override
    public void setActionListener(ActionListener listener) 
    {
        this.recibidoButton.addActionListener(listener);
        this.iniciarConexionButton.addActionListener(listener);
        this.configurationButton.addActionListener(listener);
    }
    
    @Override
    public void nuevaSolicitud(Solicitud sol)
    {
        this.modeloListaSolicitudes.addElement(sol);
    }
    
    @Override
    public void eliminaSolicitud(Solicitud sol)
    {
        this.modeloListaSolicitudes.removeElement(sol);
    }
    
    @Override
    public Solicitud getSolicitudSelected()
    {
        Solicitud sol=(Solicitud) this.listaSolicitudes.getSelectedValue();
        return sol;
    }
    
    public void updateTextArea(String text){
        this.infoTextArea.setText(text);
    }
   

}
