/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.botonantipanico.Emisor;

import excepciones.PortOrIpInvalidException;
import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;




/**
 *
 * @author franc
 */
public class ConfiguracionEmisor extends javax.swing.JFrame 
{
    private ControladorEmisor parent = null;
    private ArrayList<JCheckBox> checkBoxs = new ArrayList<JCheckBox>();
    /**
     * Creates new form ConfiguracionEmisor
     */
    public ConfiguracionEmisor(ControladorEmisor parent) 
    {
        initComponents();
        this.setVisible(false);
        this.parent=parent;
        
        this.checkBoxs.add(this.asistenciaMedicaCheckBox);
        this.checkBoxs.add(this.seguridadCheckBox);
        this.checkBoxs.add(this.focoIncendioCheckBox);
        for(JCheckBox box : this.checkBoxs)
        {
            box.setSelected(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        portTextField = new javax.swing.JTextField();
        ipTextField = new javax.swing.JTextField();
        portLabel = new javax.swing.JLabel();
        ipLabel = new javax.swing.JLabel();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        nroPuestoTextField = new javax.swing.JTextField();
        nroPuestoLabel = new javax.swing.JLabel();
        asistenciaMedicaCheckBox = new javax.swing.JCheckBox();
        focoIncendioCheckBox = new javax.swing.JCheckBox();
        seguridadCheckBox = new javax.swing.JCheckBox();
        todasCheckBox = new javax.swing.JCheckBox();
        solicitudesLabel = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        portLabel.setText("Puerto");

        ipLabel.setText("IP");

        saveButton.setText("Guardar");
        saveButton.setActionCommand("saveAction");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.setActionCommand("cancelAction");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        nroPuestoLabel.setText("Puesto");

        asistenciaMedicaCheckBox.setText("Asistencia Medica");
        asistenciaMedicaCheckBox.setName("Asistencia medica"); // NOI18N

        focoIncendioCheckBox.setText("Notificacion incendio");
        focoIncendioCheckBox.setName("Notificacion incendio"); // NOI18N

        seguridadCheckBox.setLabel("Solicitud seguridad");
        seguridadCheckBox.setName("Solicitud seguridad"); // NOI18N

        todasCheckBox.setText("Todas");
        todasCheckBox.setName("Todas"); // NOI18N

        solicitudesLabel.setText("Configuracion solicitudes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(28, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(focoIncendioCheckBox)
                            .addComponent(asistenciaMedicaCheckBox)
                            .addComponent(solicitudesLabel))
                        .addGap(123, 123, 123)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seguridadCheckBox)
                            .addComponent(todasCheckBox))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nroPuestoLabel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ipLabel)
                                .addComponent(portLabel)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nroPuestoTextField)
                            .addComponent(portTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(solicitudesLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asistenciaMedicaCheckBox)
                    .addComponent(seguridadCheckBox))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(focoIncendioCheckBox)
                    .addComponent(todasCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ipTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ipLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(portLabel)
                    .addComponent(portTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nroPuestoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nroPuestoLabel))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String puerto=this.portTextField.getText();
        String IP=this.ipTextField.getText();
        String puesto=this.nroPuestoTextField.getText();
        if(this.parent.validaConexion(IP, puerto))
        {
            this.parent.setPort(puerto);
            this.parent.setIP(IP);
            this.parent.setNroPuesto(Integer.parseInt(puesto));
            this.setActions();
            this.dispose();
        }
        else
        {
            this.cancelButtonActionPerformed(evt);
            try{
                this.puertoIPInvalidos();
            }
            catch(PortOrIpInvalidException e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }

    }//GEN-LAST:event_saveButtonActionPerformed

    
    public void puertoIPInvalidos() throws PortOrIpInvalidException
    {
        throw new PortOrIpInvalidException("PUERTO o IP invalido");
    }
        
    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.portTextField.setText(this.parent.getPort());
        this.ipTextField.setText(this.parent.getIP());
        this.nroPuestoTextField.setText(String.valueOf(this.parent.getNroPuesto()));
        HashMap<String,Boolean> acc = this.parent.getHash();
        this.asistenciaMedicaCheckBox.setSelected(acc.get("Asistencia medica"));
        this.seguridadCheckBox.setSelected(acc.get("Solicitud seguridad"));
        this.focoIncendioCheckBox.setSelected(acc.get("Notificacion incendio"));
        if(evt.getActionCommand().equals("cancelAction")) //que cierre si viene de cancel solamente
            this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    public void setActions(){
        
        HashMap<String,Boolean> acciones = new HashMap(); 
        for(JCheckBox check : this.checkBoxs )
        {
            acciones.put(check.getName(),check.isSelected());
        }

        this.parent.setActions(acciones);
        
    }
    
    
    public void setMainConfiguration(HashMap<String,Boolean> acciones,String IP,String port , int nroPuesto)
    {
        this.asistenciaMedicaCheckBox.setSelected(acciones.get("Asistencia medica"));
        this.seguridadCheckBox.setSelected(acciones.get("Solicitud seguridad"));
        this.focoIncendioCheckBox.setSelected(acciones.get("Notificacion incendio"));
        this.ipTextField.setText(IP);
        this.portTextField.setText(port);
        this.nroPuestoTextField.setText(String.valueOf(nroPuesto));
    }
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox asistenciaMedicaCheckBox;
    private javax.swing.JButton cancelButton;
    private javax.swing.JCheckBox focoIncendioCheckBox;
    private javax.swing.JLabel ipLabel;
    private javax.swing.JTextField ipTextField;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel nroPuestoLabel;
    private javax.swing.JTextField nroPuestoTextField;
    private javax.swing.JLabel portLabel;
    private javax.swing.JTextField portTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JCheckBox seguridadCheckBox;
    private javax.swing.JLabel solicitudesLabel;
    private javax.swing.JCheckBox todasCheckBox;
    // End of variables declaration//GEN-END:variables
}
