/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.botonantipanico.Emisor;

import java.awt.event.ActionListener;
import java.util.HashMap;
/**
 *
 * @author franc
 */
public class vistaEmisor extends javax.swing.JFrame implements IVistaEmisor
{


    /**
     * Creates new form vistaEmisor
     */
    public vistaEmisor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        asistenciaMedicaButton = new javax.swing.JButton();
        seguridadButton = new javax.swing.JButton();
        incendioButton = new javax.swing.JButton();
        labelSolicitudes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaReportes = new javax.swing.JTextArea();
        labelReportes = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuEdit = new javax.swing.JMenu();
        configurationItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emisor");

        asistenciaMedicaButton.setText("Asistencia medica");
        asistenciaMedicaButton.setActionCommand("asistenciaMedica");
        asistenciaMedicaButton.setName("\"Asistencia medica\""); // NOI18N
        asistenciaMedicaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asistenciaMedicaButtonActionPerformed(evt);
            }
        });

        seguridadButton.setText("Seguridad");
        seguridadButton.setActionCommand("solicitudSeguridad");
        seguridadButton.setName("Solicitud seguridad"); // NOI18N
        seguridadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seguridadButtonActionPerformed(evt);
            }
        });

        incendioButton.setText("Incendio");
        incendioButton.setToolTipText("");
        incendioButton.setActionCommand("notificarIncendio");
        incendioButton.setName("Notificacion incendio"); // NOI18N
        incendioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                incendioButtonActionPerformed(evt);
            }
        });

        labelSolicitudes.setText("Solicitudes");

        textAreaReportes.setColumns(20);
        textAreaReportes.setRows(5);
        textAreaReportes.setText(""
        );
        jScrollPane1.setViewportView(textAreaReportes);

        labelReportes.setText("Reportes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(labelSolicitudes)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(asistenciaMedicaButton)
                        .addGap(36, 36, 36)
                        .addComponent(seguridadButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(incendioButton)
                        .addGap(25, 25, 25))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelReportes)
                        .addGap(0, 348, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(labelSolicitudes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(asistenciaMedicaButton)
                    .addComponent(incendioButton)
                    .addComponent(seguridadButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(labelReportes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jMenu1.setText("File");
        menuBar.add(jMenu1);

        menuEdit.setText("Edit");

        configurationItem.setText("Configuracion");
        configurationItem.setActionCommand("configurationOpen");
        configurationItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurationItemActionPerformed(evt);
            }
        });
        menuEdit.add(configurationItem);

        menuBar.add(menuEdit);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void asistenciaMedicaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asistenciaMedicaButtonActionPerformed
        
           
    }//GEN-LAST:event_asistenciaMedicaButtonActionPerformed

    private void incendioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_incendioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_incendioButtonActionPerformed

    private void seguridadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seguridadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seguridadButtonActionPerformed

    private void configurationItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurationItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_configurationItemActionPerformed

    
        @Override
	public void setActionListener(ActionListener listener)
	{
            this.asistenciaMedicaButton.addActionListener(listener);
            this.incendioButton.addActionListener(listener);
            this.seguridadButton.addActionListener(listener);
            this.configurationItem.addActionListener(listener);
	}
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaEmisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaEmisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaEmisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaEmisor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaEmisor().setVisible(true);
            }
        });
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton asistenciaMedicaButton;
    private javax.swing.JMenuItem configurationItem;
    private javax.swing.JButton incendioButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelReportes;
    private javax.swing.JLabel labelSolicitudes;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuEdit;
    private javax.swing.JButton seguridadButton;
    private javax.swing.JTextArea textAreaReportes;
    // End of variables declaration//GEN-END:variables

    
@Override
public void changeNotifications(HashMap<String,Boolean> hash)
{
    System.out.println(hash);
    this.asistenciaMedicaButton.setEnabled(hash.get("Asistencia medica"));
    this.incendioButton.setEnabled(hash.get("Notificacion incendio"));
    this.seguridadButton.setEnabled(hash.get("Solicitud seguridad"));
}

    @Override
    public void updateText(String txt) {
        this.textAreaReportes.append(txt + "\n");
    }

}

